name: BaaS Publications
favicon: null
layout_spectrum: 0.238033642526716
typography_spectrum: 0.5431649622041732
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.0802221610210836
  lightness: 0.92843645834364
  saturation: 0.33848636667244136
  rhythmicContrast: 0.40838866238482296
purpose: []
